#只有在Ecco节下的东西才会被读取
[Ecco]
#菜单设置，以.设置菜单层级
#此处设置为id，在lang/user_setting.toml中设置id对应的翻译
name="TestCategory.TestItem"
#花费多少金钱
cost=0
#使用tcl编写的脚本

script="""
give $caller_index "weapon_9mmhandgun"
set player_name [Player::GetName $caller_index]
set player_id [Player::GetSteamId $caller_index]
saytext $caller_index "${player_name} 在小心的说悄悄话 ${player_id}"
"""
flags=0
#需要Precache的那些资源
precaches=[]
sound_precaches=[]