[Lang]
not_enough_credits="{0} needs ${1}, but you only have ${2}."
ecco_menu_back="Back"
ecco_menu_prev_page="Previous"
ecco_menu_next_page="Next"
ecco_menu_exit="Exit"
ecco_menu_root="\\w[\\yEcco Store\\w]\n\\c============"
ecco_eval_exception="在购买{0}时发生了一个错误，请截图告知管理员"
ecco_cmd_access_deny="你不能使用这个命令！"
ecco_scripts_reloading="正在重载脚本及菜单……"
ecco_scripts_reloaded="脚本及菜单重载完毕！"
ecco_cmd_usage="用法:"