#只有在Ecco节下的东西才会被读取
[Ecco]
#菜单设置，以.设置菜单层级
#此处设置为id，在lang/user_setting.toml中设置id对应的翻译
name="TestCategory.TestItem"
#花费多少金钱
cost=0
#使用ChaiScript编写的脚本
# 传入CEccoPlayer caller
# CEccoPlayer
#  |- string: GetSteamId()
#  |- number: GetCredits()
#  |- string: GetName()
#  |- string: GetLang()
#  |- void: SetCredits(number)
#  |- void: AddCredits(number)
#  |- number: m_iScore
# 传入CEccoBuyItem buy_item
# CEccoBuyItem
#  |- number: m_iCost
#  |- number: m_bitFlags
#  |- string: m_szId
#  |- string: GetDisplayName(CEccoPlayer)
# 需要设置ret为true方可成功购买
script="""
give(caller, "weapon_9mmhandgun")
saytext(caller, caller.GetName() + " 在小心的说悄悄话 " + caller.GetSteamId())
saytext(caller, caller.GetLang() + caller.GetCredits().to_string())
ret=true
"""
flags=0
#需要Precache的那些资源
precaches=[]
sound_precaches=[]