#include <string>
#include <filesystem>

#include "tcl_loader.h"
#include "tcl_dynamic.h"
#undef DLLEXPORT

#include <extdll.h>
#include <meta_api.h>
#include "meta_utility.h"


#ifdef _WIN32
#define GET_PROC_ADDR GetProcAddress
#define LIB_HANDLE HMODULE
#define LOAD_LIB(path) LoadLibraryA((path).c_str())
#define FREE_LIB FreeLibrary
#else
#define GET_PROC_ADDR dlsym
#define LIB_HANDLE void*
#define LOAD_LIB(path) dlopen((path).c_str(), RTLD_NOW)
#define FREE_LIB dlclose
#endif


static LIB_HANDLE g_TclLibHandle = nullptr;
static LIB_HANDLE g_Zlib1Handle = nullptr;
static LIB_HANDLE g_libtommathHandle = nullptr;

// 辅助宏
#define LOAD_TCL_API(name) \
    name = (decltype(name))GET_PROC_ADDR(g_TclLibHandle, #name); \
    if (!name) { \
        LOG_ERROR(PLID, "Can not load tcl91 API: %s\n", #name); \
        return false; \
    }

#pragma region Vars
PFN_Tcl_Free Tcl_Free = nullptr;
PFN_Tcl_DbCkfree Tcl_DbCkfree = nullptr;
PFN_Tcl_DeleteFileHandler Tcl_DeleteFileHandler = nullptr;
PFN_Tcl_SetTimer Tcl_SetTimer = nullptr;
PFN_Tcl_Sleep Tcl_Sleep = nullptr;
PFN_Tcl_WaitForEvent Tcl_WaitForEvent = nullptr;
PFN_Tcl_AppendStringsToObj Tcl_AppendStringsToObj = nullptr;
PFN_TclFreeObj TclFreeObj = nullptr;
PFN_Tcl_InvalidateStringRep Tcl_InvalidateStringRep = nullptr;
PFN_Tcl_SetDoubleObj Tcl_SetDoubleObj = nullptr;
PFN_Tcl_SetObjLength Tcl_SetObjLength = nullptr;
PFN_Tcl_AllowExceptions Tcl_AllowExceptions = nullptr;
PFN_Tcl_AppendResult Tcl_AppendResult = nullptr;
PFN_Tcl_AsyncDelete Tcl_AsyncDelete = nullptr;
PFN_Tcl_AsyncInvoke Tcl_AsyncInvoke = nullptr;
PFN_Tcl_AsyncMark Tcl_AsyncMark = nullptr;
PFN_Tcl_AsyncReady Tcl_AsyncReady = nullptr;
PFN_Tcl_CommandComplete Tcl_CommandComplete = nullptr;
PFN_Tcl_DeleteHashEntry Tcl_DeleteHashEntry = nullptr;
PFN_Tcl_DeleteHashTable Tcl_DeleteHashTable = nullptr;
PFN_Tcl_DeleteInterp Tcl_DeleteInterp = nullptr;
PFN_Tcl_DetachPids Tcl_DetachPids = nullptr;
PFN_Tcl_DeleteTimerHandler Tcl_DeleteTimerHandler = nullptr;
PFN_Tcl_DeleteTrace Tcl_DeleteTrace = nullptr;
PFN_Tcl_DoOneEvent Tcl_DoOneEvent = nullptr;
PFN_Tcl_DoWhenIdle Tcl_DoWhenIdle = nullptr;
PFN_Tcl_DStringEndSublist Tcl_DStringEndSublist = nullptr;
PFN_Tcl_DStringFree Tcl_DStringFree = nullptr;
PFN_Tcl_DStringInit Tcl_DStringInit = nullptr;
PFN_Tcl_DStringStartSublist Tcl_DStringStartSublist = nullptr;
PFN_Tcl_Eof Tcl_Eof = nullptr;
PFN_Tcl_ExprString Tcl_ExprString = nullptr;
PFN_Tcl_Finalize Tcl_Finalize = nullptr;
PFN_Tcl_Flush Tcl_Flush = nullptr;
PFN_Tcl_GetChannelBufferSize Tcl_GetChannelBufferSize = nullptr;
PFN_Tcl_GetChannelMode Tcl_GetChannelMode = nullptr;
PFN_Tcl_GetErrno Tcl_GetErrno = nullptr;
PFN_Tcl_GetPathType Tcl_GetPathType = nullptr;
PFN_Tcl_Gets Tcl_Gets = nullptr;
PFN_Tcl_GetsObj Tcl_GetsObj = nullptr;
PFN_Tcl_GetServiceMode Tcl_GetServiceMode = nullptr;
PFN_Tcl_GetStdChannel Tcl_GetStdChannel = nullptr;
PFN_Tcl_Init Tcl_Init = nullptr;
PFN_Tcl_InputBlocked Tcl_InputBlocked = nullptr;
PFN_Tcl_InputBuffered Tcl_InputBuffered = nullptr;
PFN_Tcl_InterpDeleted Tcl_InterpDeleted = nullptr;
PFN_Tcl_IsSafe Tcl_IsSafe = nullptr;
PFN_Tcl_MakeFileChannel Tcl_MakeFileChannel = nullptr;
PFN_Tcl_MakeTcpClientChannel Tcl_MakeTcpClientChannel = nullptr;
PFN_Tcl_NotifyChannel Tcl_NotifyChannel = nullptr;
PFN_Tcl_Preserve Tcl_Preserve = nullptr;
PFN_Tcl_PutEnv Tcl_PutEnv = nullptr;
PFN_Tcl_QueueEvent Tcl_QueueEvent = nullptr;
PFN_Tcl_ReapDetachedProcs Tcl_ReapDetachedProcs = nullptr;
PFN_Tcl_RegisterObjType Tcl_RegisterObjType = nullptr;
PFN_Tcl_Release Tcl_Release = nullptr;
PFN_Tcl_ResetResult Tcl_ResetResult = nullptr;
PFN_Tcl_ScanElement Tcl_ScanElement = nullptr;
PFN_Tcl_ServiceAll Tcl_ServiceAll = nullptr;
PFN_Tcl_ServiceEvent Tcl_ServiceEvent = nullptr;
PFN_Tcl_SetErrno Tcl_SetErrno = nullptr;
PFN_Tcl_SetErrorCode Tcl_SetErrorCode = nullptr;
PFN_Tcl_SetMaxBlockTime Tcl_SetMaxBlockTime = nullptr;
PFN_Tcl_SetServiceMode Tcl_SetServiceMode = nullptr;
PFN_Tcl_SetStdChannel Tcl_SetStdChannel = nullptr;
PFN_Tcl_SourceRCFile Tcl_SourceRCFile = nullptr;
PFN_Tcl_VarEval Tcl_VarEval = nullptr;
PFN_Tcl_DumpActiveMemory Tcl_DumpActiveMemory = nullptr;
PFN_Tcl_ValidateAllMemory Tcl_ValidateAllMemory = nullptr;
PFN_Tcl_WaitPid Tcl_WaitPid = nullptr;
PFN_Tcl_InitMemory Tcl_InitMemory = nullptr;
PFN_Tcl_GetStackedChannel Tcl_GetStackedChannel = nullptr;
PFN_Tcl_SetMainLoop Tcl_SetMainLoop = nullptr;
PFN_Tcl_CreateEncoding Tcl_CreateEncoding = nullptr;
PFN_Tcl_FinalizeThread Tcl_FinalizeThread = nullptr;
PFN_Tcl_FinalizeNotifier Tcl_FinalizeNotifier = nullptr;
PFN_Tcl_FreeEncoding Tcl_FreeEncoding = nullptr;
PFN_Tcl_GetCurrentThread Tcl_GetCurrentThread = nullptr;
PFN_Tcl_GetEncoding Tcl_GetEncoding = nullptr;
PFN_Tcl_GetEncodingNames Tcl_GetEncodingNames = nullptr;
PFN_Tcl_MutexLock Tcl_MutexLock = nullptr;
PFN_Tcl_MutexUnlock Tcl_MutexUnlock = nullptr;
PFN_Tcl_ConditionNotify Tcl_ConditionNotify = nullptr;
PFN_TclNumUtfChars TclNumUtfChars = nullptr;
PFN_Tcl_ThreadAlert Tcl_ThreadAlert = nullptr;
PFN_Tcl_UniCharAtIndex Tcl_UniCharAtIndex = nullptr;
PFN_Tcl_UniCharToLower Tcl_UniCharToLower = nullptr;
PFN_Tcl_UniCharToTitle Tcl_UniCharToTitle = nullptr;
PFN_Tcl_UniCharToUpper Tcl_UniCharToUpper = nullptr;
PFN_Tcl_UniCharToUtf Tcl_UniCharToUtf = nullptr;
PFN_TclUtfCharComplete TclUtfCharComplete = nullptr;
PFN_Tcl_UtfToLower Tcl_UtfToLower = nullptr;
PFN_Tcl_UtfToTitle Tcl_UtfToTitle = nullptr;
PFN_Tcl_UtfToUpper Tcl_UtfToUpper = nullptr;
PFN_Tcl_WriteObj Tcl_WriteObj = nullptr;
PFN_Tcl_AlertNotifier Tcl_AlertNotifier = nullptr;
PFN_Tcl_ServiceModeHook Tcl_ServiceModeHook = nullptr;
PFN_Tcl_UniCharIsAlnum Tcl_UniCharIsAlnum = nullptr;
PFN_Tcl_UniCharIsAlpha Tcl_UniCharIsAlpha = nullptr;
PFN_Tcl_UniCharIsDigit Tcl_UniCharIsDigit = nullptr;
PFN_Tcl_UniCharIsLower Tcl_UniCharIsLower = nullptr;
PFN_Tcl_UniCharIsSpace Tcl_UniCharIsSpace = nullptr;
PFN_Tcl_UniCharIsUpper Tcl_UniCharIsUpper = nullptr;
PFN_Tcl_UniCharIsWordChar Tcl_UniCharIsWordChar = nullptr;
PFN_Tcl_Char16Len Tcl_Char16Len = nullptr;
PFN_Tcl_FreeParse Tcl_FreeParse = nullptr;
PFN_Tcl_Chdir Tcl_Chdir = nullptr;
PFN_Tcl_Access Tcl_Access = nullptr;
PFN_Tcl_Stat Tcl_Stat = nullptr;
PFN_TclUtfNcmp TclUtfNcmp = nullptr;
PFN_Tcl_UniCharIsControl Tcl_UniCharIsControl = nullptr;
PFN_Tcl_UniCharIsGraph Tcl_UniCharIsGraph = nullptr;
PFN_Tcl_UniCharIsPrint Tcl_UniCharIsPrint = nullptr;
PFN_Tcl_UniCharIsPunct Tcl_UniCharIsPunct = nullptr;
PFN_TclGetCharLength TclGetCharLength = nullptr;
PFN_TclGetUniChar TclGetUniChar = nullptr;
PFN_Tcl_GetChannelNames Tcl_GetChannelNames = nullptr;
PFN_Tcl_ConditionFinalize Tcl_ConditionFinalize = nullptr;
PFN_Tcl_MutexFinalize Tcl_MutexFinalize = nullptr;
PFN_Tcl_GetTopChannel Tcl_GetTopChannel = nullptr;
PFN_Tcl_ChannelBuffered Tcl_ChannelBuffered = nullptr;
PFN_Tcl_JoinThread Tcl_JoinThread = nullptr;
PFN_Tcl_IsChannelShared Tcl_IsChannelShared = nullptr;
PFN_Tcl_CutChannel Tcl_CutChannel = nullptr;
PFN_Tcl_SpliceChannel Tcl_SpliceChannel = nullptr;
PFN_Tcl_ClearChannelHandlers Tcl_ClearChannelHandlers = nullptr;
PFN_Tcl_IsChannelExisting Tcl_IsChannelExisting = nullptr;
PFN_Tcl_InitObjHashTable Tcl_InitObjHashTable = nullptr;
PFN_Tcl_GetChannelThread Tcl_GetChannelThread = nullptr;
PFN_Tcl_IsStandardChannel Tcl_IsStandardChannel = nullptr;
PFN_Tcl_FSCreateDirectory Tcl_FSCreateDirectory = nullptr;
PFN_Tcl_FSDeleteFile Tcl_FSDeleteFile = nullptr;
PFN_Tcl_FSLstat Tcl_FSLstat = nullptr;
PFN_Tcl_FSUtime Tcl_FSUtime = nullptr;
PFN_Tcl_FSStat Tcl_FSStat = nullptr;
PFN_Tcl_FSAccess Tcl_FSAccess = nullptr;
PFN_Tcl_FSChdir Tcl_FSChdir = nullptr;
PFN_Tcl_FSEvalFile Tcl_FSEvalFile = nullptr;
PFN_Tcl_FSUnregister Tcl_FSUnregister = nullptr;
PFN_Tcl_FSGetPathType Tcl_FSGetPathType = nullptr;
PFN_Tcl_OutputBuffered Tcl_OutputBuffered = nullptr;
PFN_Tcl_FSMountsChanged Tcl_FSMountsChanged = nullptr;
PFN_Tcl_GetTime Tcl_GetTime = nullptr;
PFN_Tcl_DictObjDone Tcl_DictObjDone = nullptr;
PFN_Tcl_DeleteNamespace Tcl_DeleteNamespace = nullptr;
PFN_Tcl_LimitReady Tcl_LimitReady = nullptr;
PFN_Tcl_LimitCheck Tcl_LimitCheck = nullptr;
PFN_Tcl_LimitExceeded Tcl_LimitExceeded = nullptr;
PFN_Tcl_LimitTypeEnabled Tcl_LimitTypeEnabled = nullptr;
PFN_Tcl_LimitTypeExceeded Tcl_LimitTypeExceeded = nullptr;
PFN_Tcl_LimitTypeSet Tcl_LimitTypeSet = nullptr;
PFN_Tcl_LimitTypeReset Tcl_LimitTypeReset = nullptr;
PFN_Tcl_LimitGetCommands Tcl_LimitGetCommands = nullptr;
PFN_Tcl_LimitGetGranularity Tcl_LimitGetGranularity = nullptr;
PFN_Tcl_SaveInterpState Tcl_SaveInterpState = nullptr;
PFN_Tcl_DiscardInterpState Tcl_DiscardInterpState = nullptr;
PFN_Tcl_IsEnsemble Tcl_IsEnsemble = nullptr;
PFN_Tcl_SetBignumObj Tcl_SetBignumObj = nullptr;
PFN_Tcl_SetChannelError Tcl_SetChannelError = nullptr;
PFN_Tcl_GetChannelError Tcl_GetChannelError = nullptr;
PFN_Tcl_SetEncodingSearchPath Tcl_SetEncodingSearchPath = nullptr;
PFN_Tcl_Canceled Tcl_Canceled = nullptr;
PFN_Tcl_GetFSDeviceFromStat Tcl_GetFSDeviceFromStat = nullptr;
PFN_Tcl_GetFSInodeFromStat Tcl_GetFSInodeFromStat = nullptr;
PFN_Tcl_GetModeFromStat Tcl_GetModeFromStat = nullptr;
PFN_Tcl_GetLinkCountFromStat Tcl_GetLinkCountFromStat = nullptr;
PFN_Tcl_GetUserIdFromStat Tcl_GetUserIdFromStat = nullptr;
PFN_Tcl_GetGroupIdFromStat Tcl_GetGroupIdFromStat = nullptr;
PFN_Tcl_GetDeviceTypeFromStat Tcl_GetDeviceTypeFromStat = nullptr;
PFN_Tcl_GetBlockSizeFromStat Tcl_GetBlockSizeFromStat = nullptr;
PFN_Tcl_GetErrorLine Tcl_GetErrorLine = nullptr;
PFN_Tcl_SetErrorLine Tcl_SetErrorLine = nullptr;
PFN_Tcl_InterpActive Tcl_InterpActive = nullptr;
PFN_Tcl_BackgroundException Tcl_BackgroundException = nullptr;
PFN_Tcl_ZlibStreamEof Tcl_ZlibStreamEof = nullptr;
PFN_Tcl_ZlibStreamChecksum Tcl_ZlibStreamChecksum = nullptr;
PFN_Tcl_ZlibStreamClose Tcl_ZlibStreamClose = nullptr;
PFN_Tcl_ZlibStreamReset Tcl_ZlibStreamReset = nullptr;
PFN_Tcl_FreeInternalRep Tcl_FreeInternalRep = nullptr;
PFN_Tcl_HasStringRep Tcl_HasStringRep = nullptr;
PFN_Tcl_IncrRefCount Tcl_IncrRefCount = nullptr;
PFN_Tcl_DecrRefCount Tcl_DecrRefCount = nullptr;
PFN_Tcl_IsShared Tcl_IsShared = nullptr;
PFN_Tcl_UtfToUniChar Tcl_UtfToUniChar = nullptr;
PFN_Tcl_UtfCharComplete Tcl_UtfCharComplete = nullptr;
PFN_Tcl_UniCharLen Tcl_UniCharLen = nullptr;
PFN_Tcl_NumUtfChars Tcl_NumUtfChars = nullptr;
PFN_Tcl_GetCharLength Tcl_GetCharLength = nullptr;
PFN_Tcl_GetUniChar Tcl_GetUniChar = nullptr;
PFN_Tcl_GetEncodingNulLength Tcl_GetEncodingNulLength = nullptr;
PFN_Tcl_UtfNcmp Tcl_UtfNcmp = nullptr;
PFN_Tcl_IsEmpty Tcl_IsEmpty = nullptr;
PFN_TclUnusedStubEntry TclUnusedStubEntry = nullptr;
#pragma endregion

bool LoadTCLLibrary() {
    std::filesystem::path tcllib(EccoMetaUtility::GetGameDir());
	tcllib.append("addons/ecco/tcl/");
#ifdef _WIN32
    g_libtommathHandle = LOAD_LIB(tcllib.string() + "libtommath.dll");
    g_Zlib1Handle = LOAD_LIB(tcllib.string() + "zlib1.dll");
    g_TclLibHandle = LOAD_LIB(tcllib.string() + "tcl91.dll");
#else
    g_libtommathHandle = LOAD_LIB(tcllib.string() + "libtommath.so");
    g_Zlib1Handle = LOAD_LIB(tcllib.string() + "zlib1.so");
    g_TclLibHandle = LOAD_LIB(tcllib.string() + "tcl91.so");
#endif
    if (!g_libtommathHandle || !g_Zlib1Handle || !g_TclLibHandle) {
		LOG_ERROR(PLID, "Can not load tcl91 library\n");
        return false;
    }

    // 依次加载所有API
    LOAD_TCL_API(Tcl_Free);
    LOAD_TCL_API(Tcl_DbCkfree);
    LOAD_TCL_API(Tcl_DeleteFileHandler);
    LOAD_TCL_API(Tcl_SetTimer);
    LOAD_TCL_API(Tcl_Sleep);
    LOAD_TCL_API(Tcl_WaitForEvent);
    LOAD_TCL_API(Tcl_AppendStringsToObj);
    LOAD_TCL_API(TclFreeObj);
    LOAD_TCL_API(Tcl_InvalidateStringRep);
    LOAD_TCL_API(Tcl_SetDoubleObj);
    LOAD_TCL_API(Tcl_SetObjLength);
    LOAD_TCL_API(Tcl_AllowExceptions);
    LOAD_TCL_API(Tcl_AppendResult);
    LOAD_TCL_API(Tcl_AsyncDelete);
    LOAD_TCL_API(Tcl_AsyncInvoke);
    LOAD_TCL_API(Tcl_AsyncMark);
    LOAD_TCL_API(Tcl_AsyncReady);
    LOAD_TCL_API(Tcl_CommandComplete);
    LOAD_TCL_API(Tcl_DeleteHashEntry);
    LOAD_TCL_API(Tcl_DeleteHashTable);
    LOAD_TCL_API(Tcl_DeleteInterp);
    LOAD_TCL_API(Tcl_DetachPids);
    LOAD_TCL_API(Tcl_DeleteTimerHandler);
    LOAD_TCL_API(Tcl_DeleteTrace);
    LOAD_TCL_API(Tcl_DoOneEvent);
    LOAD_TCL_API(Tcl_DoWhenIdle);
    LOAD_TCL_API(Tcl_DStringEndSublist);
    LOAD_TCL_API(Tcl_DStringFree);
    LOAD_TCL_API(Tcl_DStringInit);
    LOAD_TCL_API(Tcl_DStringStartSublist);
    LOAD_TCL_API(Tcl_Eof);
    LOAD_TCL_API(Tcl_ExprString);
    LOAD_TCL_API(Tcl_Finalize);
    LOAD_TCL_API(Tcl_Flush);
    LOAD_TCL_API(Tcl_GetChannelBufferSize);
    LOAD_TCL_API(Tcl_GetChannelMode);
    LOAD_TCL_API(Tcl_GetErrno);
    LOAD_TCL_API(Tcl_GetPathType);
    LOAD_TCL_API(Tcl_Gets);
    LOAD_TCL_API(Tcl_GetsObj);
    LOAD_TCL_API(Tcl_GetServiceMode);
    LOAD_TCL_API(Tcl_GetStdChannel);
    LOAD_TCL_API(Tcl_Init);
    LOAD_TCL_API(Tcl_InputBlocked);
    LOAD_TCL_API(Tcl_InputBuffered);
    LOAD_TCL_API(Tcl_InterpDeleted);
    LOAD_TCL_API(Tcl_IsSafe);
    LOAD_TCL_API(Tcl_MakeFileChannel);
    LOAD_TCL_API(Tcl_MakeTcpClientChannel);
    LOAD_TCL_API(Tcl_NotifyChannel);
    LOAD_TCL_API(Tcl_Preserve);
    LOAD_TCL_API(Tcl_PutEnv);
    LOAD_TCL_API(Tcl_QueueEvent);
    LOAD_TCL_API(Tcl_ReapDetachedProcs);
    LOAD_TCL_API(Tcl_RegisterObjType);
    LOAD_TCL_API(Tcl_Release);
    LOAD_TCL_API(Tcl_ResetResult);
    LOAD_TCL_API(Tcl_ScanElement);
    LOAD_TCL_API(Tcl_ServiceAll);
    LOAD_TCL_API(Tcl_ServiceEvent);
    LOAD_TCL_API(Tcl_SetErrno);
    LOAD_TCL_API(Tcl_SetErrorCode);
    LOAD_TCL_API(Tcl_SetMaxBlockTime);
    LOAD_TCL_API(Tcl_SetServiceMode);
    LOAD_TCL_API(Tcl_SetStdChannel);
    LOAD_TCL_API(Tcl_SourceRCFile);
    LOAD_TCL_API(Tcl_VarEval);
    LOAD_TCL_API(Tcl_DumpActiveMemory);
    LOAD_TCL_API(Tcl_ValidateAllMemory);
    LOAD_TCL_API(Tcl_WaitPid);
    LOAD_TCL_API(Tcl_InitMemory);
    LOAD_TCL_API(Tcl_GetStackedChannel);
    LOAD_TCL_API(Tcl_SetMainLoop);
    LOAD_TCL_API(Tcl_CreateEncoding);
    LOAD_TCL_API(Tcl_FinalizeThread);
    LOAD_TCL_API(Tcl_FinalizeNotifier);
    LOAD_TCL_API(Tcl_FreeEncoding);
    LOAD_TCL_API(Tcl_GetCurrentThread);
    LOAD_TCL_API(Tcl_GetEncoding);
    LOAD_TCL_API(Tcl_GetEncodingNames);
    LOAD_TCL_API(Tcl_MutexLock);
    LOAD_TCL_API(Tcl_MutexUnlock);
    LOAD_TCL_API(Tcl_ConditionNotify);
    LOAD_TCL_API(TclNumUtfChars);
    LOAD_TCL_API(Tcl_ThreadAlert);
    LOAD_TCL_API(Tcl_UniCharAtIndex);
    LOAD_TCL_API(Tcl_UniCharToLower);
    LOAD_TCL_API(Tcl_UniCharToTitle);
    LOAD_TCL_API(Tcl_UniCharToUpper);
    LOAD_TCL_API(Tcl_UniCharToUtf);
    LOAD_TCL_API(TclUtfCharComplete);
    LOAD_TCL_API(Tcl_UtfToLower);
    LOAD_TCL_API(Tcl_UtfToTitle);
    LOAD_TCL_API(Tcl_UtfToUpper);
    LOAD_TCL_API(Tcl_WriteObj);
    LOAD_TCL_API(Tcl_AlertNotifier);
    LOAD_TCL_API(Tcl_ServiceModeHook);
    LOAD_TCL_API(Tcl_UniCharIsAlnum);
    LOAD_TCL_API(Tcl_UniCharIsAlpha);
    LOAD_TCL_API(Tcl_UniCharIsDigit);
    LOAD_TCL_API(Tcl_UniCharIsLower);
    LOAD_TCL_API(Tcl_UniCharIsSpace);
    LOAD_TCL_API(Tcl_UniCharIsUpper);
    LOAD_TCL_API(Tcl_UniCharIsWordChar);
    LOAD_TCL_API(Tcl_Char16Len);
    LOAD_TCL_API(Tcl_FreeParse);
    LOAD_TCL_API(Tcl_Chdir);
    LOAD_TCL_API(Tcl_Access);
    LOAD_TCL_API(Tcl_Stat);
    LOAD_TCL_API(TclUtfNcmp);
    LOAD_TCL_API(Tcl_UniCharIsControl);
    LOAD_TCL_API(Tcl_UniCharIsGraph);
    LOAD_TCL_API(Tcl_UniCharIsPrint);
    LOAD_TCL_API(Tcl_UniCharIsPunct);
    LOAD_TCL_API(TclGetCharLength);
    LOAD_TCL_API(TclGetUniChar);
    LOAD_TCL_API(Tcl_GetChannelNames);
    LOAD_TCL_API(Tcl_ConditionFinalize);
    LOAD_TCL_API(Tcl_MutexFinalize);
    LOAD_TCL_API(Tcl_GetTopChannel);
    LOAD_TCL_API(Tcl_ChannelBuffered);
    LOAD_TCL_API(Tcl_JoinThread);
    LOAD_TCL_API(Tcl_IsChannelShared);
    LOAD_TCL_API(Tcl_CutChannel);
    LOAD_TCL_API(Tcl_SpliceChannel);
    LOAD_TCL_API(Tcl_ClearChannelHandlers);
    LOAD_TCL_API(Tcl_IsChannelExisting);
    LOAD_TCL_API(Tcl_InitObjHashTable);
    LOAD_TCL_API(Tcl_GetChannelThread);
    LOAD_TCL_API(Tcl_IsStandardChannel);
    LOAD_TCL_API(Tcl_FSCreateDirectory);
    LOAD_TCL_API(Tcl_FSDeleteFile);
    LOAD_TCL_API(Tcl_FSLstat);
    LOAD_TCL_API(Tcl_FSUtime);
    LOAD_TCL_API(Tcl_FSStat);
    LOAD_TCL_API(Tcl_FSAccess);
    LOAD_TCL_API(Tcl_FSChdir);
    LOAD_TCL_API(Tcl_FSEvalFile);
    LOAD_TCL_API(Tcl_FSUnregister);
    LOAD_TCL_API(Tcl_FSGetPathType);
    LOAD_TCL_API(Tcl_OutputBuffered);
    LOAD_TCL_API(Tcl_FSMountsChanged);
    LOAD_TCL_API(Tcl_GetTime);
    LOAD_TCL_API(Tcl_DictObjDone);
    LOAD_TCL_API(Tcl_DeleteNamespace);
    LOAD_TCL_API(Tcl_LimitReady);
    LOAD_TCL_API(Tcl_LimitCheck);
    LOAD_TCL_API(Tcl_LimitExceeded);
    LOAD_TCL_API(Tcl_LimitTypeEnabled);
    LOAD_TCL_API(Tcl_LimitTypeExceeded);
    LOAD_TCL_API(Tcl_LimitTypeSet);
    LOAD_TCL_API(Tcl_LimitTypeReset);
    LOAD_TCL_API(Tcl_LimitGetCommands);
    LOAD_TCL_API(Tcl_LimitGetGranularity);
    LOAD_TCL_API(Tcl_SaveInterpState);
    LOAD_TCL_API(Tcl_DiscardInterpState);
    LOAD_TCL_API(Tcl_IsEnsemble);
    LOAD_TCL_API(Tcl_SetBignumObj);
    LOAD_TCL_API(Tcl_SetChannelError);
    LOAD_TCL_API(Tcl_GetChannelError);
    LOAD_TCL_API(Tcl_SetEncodingSearchPath);
    LOAD_TCL_API(Tcl_Canceled);
    LOAD_TCL_API(Tcl_GetFSDeviceFromStat);
    LOAD_TCL_API(Tcl_GetFSInodeFromStat);
    LOAD_TCL_API(Tcl_GetModeFromStat);
    LOAD_TCL_API(Tcl_GetLinkCountFromStat);
    LOAD_TCL_API(Tcl_GetUserIdFromStat);
    LOAD_TCL_API(Tcl_GetGroupIdFromStat);
    LOAD_TCL_API(Tcl_GetDeviceTypeFromStat);
    LOAD_TCL_API(Tcl_GetBlockSizeFromStat);
    LOAD_TCL_API(Tcl_GetErrorLine);
    LOAD_TCL_API(Tcl_SetErrorLine);
    LOAD_TCL_API(Tcl_InterpActive);
    LOAD_TCL_API(Tcl_BackgroundException);
    LOAD_TCL_API(Tcl_ZlibStreamEof);
    LOAD_TCL_API(Tcl_ZlibStreamChecksum);
    LOAD_TCL_API(Tcl_ZlibStreamClose);
    LOAD_TCL_API(Tcl_ZlibStreamReset);
    LOAD_TCL_API(Tcl_FreeInternalRep);
    LOAD_TCL_API(Tcl_HasStringRep);
    LOAD_TCL_API(Tcl_IncrRefCount);
    LOAD_TCL_API(Tcl_DecrRefCount);
    LOAD_TCL_API(Tcl_IsShared);
    LOAD_TCL_API(Tcl_UtfToUniChar);
    LOAD_TCL_API(Tcl_UtfCharComplete);
    LOAD_TCL_API(Tcl_UniCharLen);
    LOAD_TCL_API(Tcl_NumUtfChars);
    LOAD_TCL_API(Tcl_GetCharLength);
    LOAD_TCL_API(Tcl_GetUniChar);
    LOAD_TCL_API(Tcl_GetEncodingNulLength);
    LOAD_TCL_API(Tcl_UtfNcmp);
    LOAD_TCL_API(Tcl_IsEmpty);
    LOAD_TCL_API(TclUnusedStubEntry);
    return true;
}

void UnloadTCLLibrary() {
    if (g_TclLibHandle) {
        FREE_LIB(g_TclLibHandle);
        g_TclLibHandle = nullptr;
    }
    if (g_Zlib1Handle) {
        FREE_LIB(g_Zlib1Handle);
        g_Zlib1Handle = nullptr;
	}
    if (g_libtommathHandle) {
        FREE_LIB(g_libtommathHandle);
        g_libtommathHandle = nullptr;
    }
    Tcl_Free = nullptr;
    Tcl_DbCkfree = nullptr;
    Tcl_DeleteFileHandler = nullptr;
    Tcl_SetTimer = nullptr;
    Tcl_Sleep = nullptr;
    Tcl_WaitForEvent = nullptr;
    Tcl_AppendStringsToObj = nullptr;
    TclFreeObj = nullptr;
    Tcl_InvalidateStringRep = nullptr;
    Tcl_SetDoubleObj = nullptr;
    Tcl_SetObjLength = nullptr;
    Tcl_AllowExceptions = nullptr;
    Tcl_AppendResult = nullptr;
    Tcl_AsyncDelete = nullptr;
    Tcl_AsyncInvoke = nullptr;
    Tcl_AsyncMark = nullptr;
    Tcl_AsyncReady = nullptr;
    Tcl_CommandComplete = nullptr;
    Tcl_DeleteHashEntry = nullptr;
    Tcl_DeleteHashTable = nullptr;
    Tcl_DeleteInterp = nullptr;
    Tcl_DetachPids = nullptr;
    Tcl_DeleteTimerHandler = nullptr;
    Tcl_DeleteTrace = nullptr;
    Tcl_DoOneEvent = nullptr;
    Tcl_DoWhenIdle = nullptr;
    Tcl_DStringEndSublist = nullptr;
    Tcl_DStringFree = nullptr;
    Tcl_DStringInit = nullptr;
    Tcl_DStringStartSublist = nullptr;
    Tcl_Eof = nullptr;
    Tcl_ExprString = nullptr;
    Tcl_Finalize = nullptr;
    Tcl_Flush = nullptr;
    Tcl_GetChannelBufferSize = nullptr;
    Tcl_GetChannelMode = nullptr;
    Tcl_GetErrno = nullptr;
    Tcl_GetPathType = nullptr;
    Tcl_Gets = nullptr;
    Tcl_GetsObj = nullptr;
    Tcl_GetServiceMode = nullptr;
    Tcl_GetStdChannel = nullptr;
    Tcl_Init = nullptr;
    Tcl_InputBlocked = nullptr;
    Tcl_InputBuffered = nullptr;
    Tcl_InterpDeleted = nullptr;
    Tcl_IsSafe = nullptr;
    Tcl_MakeFileChannel = nullptr;
    Tcl_MakeTcpClientChannel = nullptr;
    Tcl_NotifyChannel = nullptr;
    Tcl_Preserve = nullptr;
    Tcl_PutEnv = nullptr;
    Tcl_QueueEvent = nullptr;
    Tcl_ReapDetachedProcs = nullptr;
    Tcl_RegisterObjType = nullptr;
    Tcl_Release = nullptr;
    Tcl_ResetResult = nullptr;
    Tcl_ScanElement = nullptr;
    Tcl_ServiceAll = nullptr;
    Tcl_ServiceEvent = nullptr;
    Tcl_SetErrno = nullptr;
    Tcl_SetErrorCode = nullptr;
    Tcl_SetMaxBlockTime = nullptr;
    Tcl_SetServiceMode = nullptr;
    Tcl_SetStdChannel = nullptr;
    Tcl_SourceRCFile = nullptr;
    Tcl_VarEval = nullptr;
    Tcl_DumpActiveMemory = nullptr;
    Tcl_ValidateAllMemory = nullptr;
    Tcl_WaitPid = nullptr;
    Tcl_InitMemory = nullptr;
    Tcl_GetStackedChannel = nullptr;
    Tcl_SetMainLoop = nullptr;
    Tcl_CreateEncoding = nullptr;
    Tcl_FinalizeThread = nullptr;
    Tcl_FinalizeNotifier = nullptr;
    Tcl_FreeEncoding = nullptr;
    Tcl_GetCurrentThread = nullptr;
    Tcl_GetEncoding = nullptr;
    Tcl_GetEncodingNames = nullptr;
    Tcl_MutexLock = nullptr;
    Tcl_MutexUnlock = nullptr;
    Tcl_ConditionNotify = nullptr;
    TclNumUtfChars = nullptr;
    Tcl_ThreadAlert = nullptr;
    Tcl_UniCharAtIndex = nullptr;
    Tcl_UniCharToLower = nullptr;
    Tcl_UniCharToTitle = nullptr;
    Tcl_UniCharToUpper = nullptr;
    Tcl_UniCharToUtf = nullptr;
    TclUtfCharComplete = nullptr;
    Tcl_UtfToLower = nullptr;
    Tcl_UtfToTitle = nullptr;
    Tcl_UtfToUpper = nullptr;
    Tcl_WriteObj = nullptr;
    Tcl_AlertNotifier = nullptr;
    Tcl_ServiceModeHook = nullptr;
    Tcl_UniCharIsAlnum = nullptr;
    Tcl_UniCharIsAlpha = nullptr;
    Tcl_UniCharIsDigit = nullptr;
    Tcl_UniCharIsLower = nullptr;
    Tcl_UniCharIsSpace = nullptr;
    Tcl_UniCharIsUpper = nullptr;
    Tcl_UniCharIsWordChar = nullptr;
    Tcl_Char16Len = nullptr;
    Tcl_FreeParse = nullptr;
    Tcl_Chdir = nullptr;
    Tcl_Access = nullptr;
    Tcl_Stat = nullptr;
    TclUtfNcmp = nullptr;
    Tcl_UniCharIsControl = nullptr;
    Tcl_UniCharIsGraph = nullptr;
    Tcl_UniCharIsPrint = nullptr;
    Tcl_UniCharIsPunct = nullptr;
    TclGetCharLength = nullptr;
    TclGetUniChar = nullptr;
    Tcl_GetChannelNames = nullptr;
    Tcl_ConditionFinalize = nullptr;
    Tcl_MutexFinalize = nullptr;
    Tcl_GetTopChannel = nullptr;
    Tcl_ChannelBuffered = nullptr;
    Tcl_JoinThread = nullptr;
    Tcl_IsChannelShared = nullptr;
    Tcl_CutChannel = nullptr;
    Tcl_SpliceChannel = nullptr;
    Tcl_ClearChannelHandlers = nullptr;
    Tcl_IsChannelExisting = nullptr;
    Tcl_InitObjHashTable = nullptr;
    Tcl_GetChannelThread = nullptr;
    Tcl_IsStandardChannel = nullptr;
    Tcl_FSCreateDirectory = nullptr;
    Tcl_FSDeleteFile = nullptr;
    Tcl_FSLstat = nullptr;
    Tcl_FSUtime = nullptr;
    Tcl_FSStat = nullptr;
    Tcl_FSAccess = nullptr;
    Tcl_FSChdir = nullptr;
    Tcl_FSEvalFile = nullptr;
    Tcl_FSUnregister = nullptr;
    Tcl_FSGetPathType = nullptr;
    Tcl_OutputBuffered = nullptr;
    Tcl_FSMountsChanged = nullptr;
    Tcl_GetTime = nullptr;
    Tcl_DictObjDone = nullptr;
    Tcl_DeleteNamespace = nullptr;
    Tcl_LimitReady = nullptr;
    Tcl_LimitCheck = nullptr;
    Tcl_LimitExceeded = nullptr;
    Tcl_LimitTypeEnabled = nullptr;
    Tcl_LimitTypeExceeded = nullptr;
    Tcl_LimitTypeSet = nullptr;
    Tcl_LimitTypeReset = nullptr;
    Tcl_LimitGetCommands = nullptr;
    Tcl_LimitGetGranularity = nullptr;
    Tcl_SaveInterpState = nullptr;
    Tcl_DiscardInterpState = nullptr;
    Tcl_IsEnsemble = nullptr;
    Tcl_SetBignumObj = nullptr;
    Tcl_SetChannelError = nullptr;
    Tcl_GetChannelError = nullptr;
    Tcl_SetEncodingSearchPath = nullptr;
    Tcl_Canceled = nullptr;
    Tcl_GetFSDeviceFromStat = nullptr;
    Tcl_GetFSInodeFromStat = nullptr;
    Tcl_GetModeFromStat = nullptr;
    Tcl_GetLinkCountFromStat = nullptr;
    Tcl_GetUserIdFromStat = nullptr;
    Tcl_GetGroupIdFromStat = nullptr;
    Tcl_GetDeviceTypeFromStat = nullptr;
    Tcl_GetBlockSizeFromStat = nullptr;
    Tcl_GetErrorLine = nullptr;
    Tcl_SetErrorLine = nullptr;
    Tcl_InterpActive = nullptr;
    Tcl_BackgroundException = nullptr;
    Tcl_ZlibStreamEof = nullptr;
    Tcl_ZlibStreamChecksum = nullptr;
    Tcl_ZlibStreamClose = nullptr;
    Tcl_ZlibStreamReset = nullptr;
    Tcl_FreeInternalRep = nullptr;
    Tcl_HasStringRep = nullptr;
    Tcl_IncrRefCount = nullptr;
    Tcl_DecrRefCount = nullptr;
    Tcl_IsShared = nullptr;
    Tcl_UtfToUniChar = nullptr;
    Tcl_UtfCharComplete = nullptr;
    Tcl_UniCharLen = nullptr;
    Tcl_NumUtfChars = nullptr;
    Tcl_GetCharLength = nullptr;
    Tcl_GetUniChar = nullptr;
    Tcl_GetEncodingNulLength = nullptr;
    Tcl_UtfNcmp = nullptr;
    Tcl_IsEmpty = nullptr;
    TclUnusedStubEntry = nullptr;
}