[Ecco.Hud]
#显示金钱 HUD 的方式
#0 为不显示
#1 为显示全部
#2 为仅显示金钱不显示金钱变化
#3 为仅显示金钱变化不显示金钱
ShowMoneyHUD=1
#金钱HUD显示位置
#范围（-1，1）
#-1和0代表居中
MainHudPosX=0.5
MainHudPosY=0.9
#加减HUD显示位置
#范围（-1，1）
#-1和0代表居中
NoticeHudPosX=0.5
NoticeHudPosY=0.858
#刷新HUD间隔
RefreshHudInterv=1.0
#金钱HUD频道
MoneyChannel=3
#金钱变更HUD频道
NotifyChannel=4

[Ecco.Path]
#数据储存位置
Data="storage"
#禁用地图文件路径
BanMaps="config/BannedMaps.txt"
#金币图标
MoneyIcon="misc_bdsc/dollar.spr"

[Ecco.Color]
#正数金钱RGBA
Positive=0xFFFF00FF
#负数金钱RGBA
Negative=0xFF0000FF
#增加金钱RGBA
Incresed=0x00FF00FF
#扣除金钱RGBA
Decresed=0xFF0000FF

[Ecco.BuyMenu]
#允许无视Trigger前缀
AllowIgnoreBuyPrefix=false
#购买指令Trigger
OpenShopTriggers=["buy", "shop"]
#命令直接购买物品时是否使用模糊匹配
UseBlurMatchForCommand=true
#是否允许死亡玩家购买
AllowDeathPlayerBuy=true
#购买后重新打开菜单
ReOpenMenuAfterBuy=true

[Ecco]
#玩家获得的分数转化为金钱的倍数
ScoreToMoneyMultiplier=1.0
#是否储存玩家金钱
#0 不储存
#1 只有系列地图储存
#2 储存
StorePlayerScore=1
#若不储存金钱，设置玩家起始资金
PlayerStartScore=0
#单张地图最大可获得金钱数目
#小于0为不限制
MoneyLimitePerMap=-1
#默认的语言
DefaultLang="cn"